### ISSUE TITLE
IFTTT

### ISSUE THREAD

**Issue by stephenturner** [roblanf/phypapers#2]
You can use [IFTTT](http://ifttt.com) to achieve the same end for free. dlvr.it looks not-free.

**Comment by ustervbo** [comment]
The problem with IFTTT is that there is no control of the flow of tweets. 

Pubmed update their feeds once a day so if you have a very broad search you will have a barrage of tweets, which is probably less than ideal

If your Pubmed RSS gives only a handful of new papers, IFTTT is ideal and very easy to set up
