### ISSUE TITLE
Tag with journal

### ISSUE THREAD

**Issue by ustervbo** [roblanf/phypapers#3]
The Journal title is stored in the RSS tag 'category' so the journal can be added as a tag to the tweets like this:

Edit the Twitter Destination, go to Advanced and check Auto-hashtag placement and select 1 tag to use. 
![journal_as_tag](https://cloud.githubusercontent.com/assets/10633028/12202541/b7b05de0-b62a-11e5-9666-329a6aa22dda.png)

As far as I can tell, IFTTT does not support this neat feature.

**Comment by roblanf** [comment]
That's a cool feature. Thanks for pointing it out. I'll mention it in the description. I guess the downside is that including the journal title can take valuable characters away from the title.

**Comment by ustervbo** [comment]
The journal is the abbreviated version. But you are right. It takes away
from the title.

For me knowing the journal helps me finding interesting papers since the
output of immunological papers is very large.

**Comment by SilasK** [comment]
It seems this feature is no longer availabe, is it?

**Comment by ustervbo** [comment]
I supposed this can be closed?
